# Usage instructions
# Building this Dockerfile
# docker built -t bootstrap . && docker run -ti bootstrap:latest bash

FROM python:3.11.2 AS basic_bootstrap
RUN apt-get update -y \
    && apt-get install software-properties-common curl git mc vim facter aptitude apt-utils apt-transport-https ca-certificates gnupg python3-pip libssl-dev libffi-dev -y \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | tee /usr/share/keyrings/cloud.google.gpg > /dev/null \
    && echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
    && apt-get update -y \
    && apt-get install google-cloud-cli -y \
    && curl https://pyenv.run | bash \
    && echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $HOME/.bashrc \
    && echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $HOME/.profile \
    && echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc \
    && echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.profile \
    && echo 'eval "$(pyenv init - bash)"' >> $HOME/.bashrc \
    && echo 'eval "$(pyenv init - bash)"' >> $HOME/.profile \
    && echo 'eval "$(pyenv virtualenv-init -)"' >> $HOME/.bashrc \
    && echo 'eval "$(pyenv virtualenv-init -)"' >> $HOME/.profile \
    && echo 'PATH="$HOME/.local/bin"' >> $HOME/.bashrc \
    && echo 'PATH="$HOME/.local/bin"' >> $HOME/.profile

FROM basic_bootstrap
RUN mkdir -p /apigee-workspace/apigee-helm/bootstrap \
    && useradd -ms /bin/bash friasc
COPY configure-pyenv.sh /apigee-workspace/apigee-helm/bootstrap/
COPY ../molecule /apigee-workspace/apigee-helm/molecule/
COPY resources /apigee-workspace/apigee-helm/resources/
COPY ../utils /apigee-workspace/apigee-helm/utils/
#COPY work_dir/bap_coe-site-packages-molecule /apigee-workspace/apigee-helm/resources/versions/3.11.2/envs/bap_coe/lib/python3.11/site-packages/

RUN bash /apigee-workspace/apigee-helm/bootstrap/configure-pyenv.sh
RUN pip install -r apigee-workspace/apigee-helm/resources/requirements.txt

#RUN mkdir -p work_dir \
#  && chmod -R +w work_dir \
#  && mkdir -p ~/.apigee-secure \
#  && cp resources/credentials.yml.template ~/.apigee-secure/credentials.yml

WORKDIR /apigee-workspace/apigee-helm
RUN chown friasc -R /apigee-workspace

ENTRYPOINT bash

